### ISSUE TITLE
use time in a bottle

### ISSUE THREAD

**Issue by Evoled** [RealMangorage/time-in-a-bottle#2]
when i right click with the bottle it writes above my hotbar TIAB API access revoked

**Comment by Evoled** [comment]
1.20.1

**Comment by Meowticia2** [comment]
> 1.20.1



> when i right click with the bottle it writes above my hotbar TIAB API access revoked

Same

**Comment by Evoled** [comment]
it works in version 1.20.1 4.0.0

**Comment by RealMangorage** [comment]
Goto config for it and remove "tiab" from "API Access", under world serverconfig
