### ISSUE TITLE
Lag with quarryplus

### ISSUE THREAD

**Issue by aqua-air** [RealMangorage/time-in-a-bottle#3]
Sanctum Network Modpack v5.7       Forge 42.7.5    MC 1.20.1
Causes lag with quarry plus. Player uses TIAB on quarry and server TPS goes from 20 to literally 5 or less. 
I see a option in config that says:
	#Mods that are blocked from having API access. Can add Tiab itself aswell
	"API Access" = [""]
This is very ambiguous and doesn't make much sense. If this is a blacklist for mods that the TIAB will not effect, please state that. Let me know what that even means, and if it is a blacklist then let me know how to format the mod name. Such as ["quarryplus, projecte"] etc... 
and if you have any other suggestions for me to stop this issue let me know
Thanks in advance! Great mod

**Comment by RealMangorage** [comment]
Its an internal thing and will be removed as it was an experiment. I plan on updating the mod to add a lot more customizability for what the bottle can do, Will be working on that after im done with school next week. So in a week or 2. 

It was basically a way to prevent a certain mod from using the API. Via code.
